//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace mono
{
	public class Global : System.Web.HttpApplication
	{
		
		protected void Application_Start (Object sender, EventArgs e)
		{
		}
		
		protected void Session_Start (Object sender, EventArgs e)
		{
		}
		
		protected void Application_BeginRequest (Object sender, EventArgs e)
		{
		}
		
		protected void Application_EndRequest (Object sender, EventArgs e)
		{
		}
		
		protected void Application_AuthenticateRequest (Object sender, EventArgs e)
		{
		}
		
		protected void Application_Error (Object sender, EventArgs e)
		{
		}
		
		protected void Session_End (Object sender, EventArgs e)
		{
		}
		
		protected void Application_End (Object sender, EventArgs e)
		{
		}
	}
}

